namespace SolvingMathProblems
{
    using ExtractData;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    static internal class Problem12
    {
        /// <summary>
        /// The sequence of triangle numbers is generated by adding the natural numbers.So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
        /// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
        /// Let us list the factors of the first seven triangle numbers:
        ///  1: 1
        ///  3: 1,3
        ///  6: 1,2,3,6
        /// 10: 1,2,5,10
        /// 15: 1,3,5,15
        /// 21: 1,3,7,21
        /// 28: 1,2,4,7,14,28
        /// We can see that 28 is the first triangle number to have over five divisors.
        /// What is the value of the first triangle number to have over five hundred divisors?
        /// <returns></returns>

        private static string _numbersSequence = FileReader.ReadData("Problem11Data.txt");
        public static decimal Answer()
        {
            decimal result = 0M;
            Int64 currentValue = 0;
            Int64 previousValue = 0;
            Int64 counter = 0;
            while (true)
            {
                currentValue = previousValue + counter;




                previousValue = currentValue;
                counter++;
                break;
            }

            return result;
        }

        private static int GetAmountOfDevisors(Int64 number)
        {
            int result = default(int);
            for (int i = 1; i < number; i++)
            {
                if (number % i == 0)
                    result++;
            }
            return result;
        }

    }
}