using System.Collections.Generic;
using System.Linq;

namespace SolvingMathProblems
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    static internal class Problem2
    {
        public static decimal Answer()
        {
            decimal result = 0M;
            List<int> fubonaci = new List<int>() { 1, 2 };
            do
            {
                fubonaci.Add(fubonaci[fubonaci.Count - 1] + fubonaci[fubonaci.Count - 2]);
            } while (fubonaci.Last() <= 4000000);

            foreach (var value in fubonaci)
            {
                if (value % 2 == 0)
                    result += value;
            }

            return result;
        }
    }
}
